name: Node.js CI

on:
  schedule:
    - cron:  '* 3 * * *'

#  issues:
#    types: [opened, edited, closed, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node atomgen.js
    - run: |
          git config --global user.name angeal185
          git config --global user.email angeal185@users.noreply.github.com
          git add *
          git commit -m "update"
          git push
